<?php

use App\Http\Controllers\Admin\LogoutController;
use Illuminate\Support\Facades\Route;
use App\Livewire\Auth\LoginComponent;
use App\Livewire\Auth\RegisterComponent;
use App\Livewire\User\HomeComponent;
use App\Livewire\User\AboutComponent;
use App\Livewire\User\AccountComponent;
use App\Livewire\User\ContactComponent;
use App\Livewire\User\PrivacyPolicyComponent;
use App\Livewire\User\TermsComponent;
use App\Livewire\User\CartComponent;
use App\Livewire\User\CheckoutComponent;
use App\Livewire\User\CompareComponent;
use App\Livewire\User\ShopComponent;
use App\Livewire\User\ShopDetailComponent;
use App\Livewire\User\WishlistComponent;
use App\Livewire\User\ReturnPolicy;
use App\Livewire\User\ShippingPolicy;
use App\Livewire\User\CouponClaim;
use App\Livewire\User\CodConversionComponent;
use App\Livewire\User\OrderComponent;
use App\Livewire\User\DeliveryInformationComponent;
use App\Livewire\User\OrderDetail;
use App\Livewire\User\Profile;
use App\Livewire\User\AddressComponent;
use App\Http\Controllers\PaymentSuccessController;
use App\Livewire\User\AllCategory;
use App\Livewire\User\OrderCompleted;
use App\Http\Controllers\ImportController;

Route::get('/', HomeComponent::class)->name('login');
Route::get('/about', AboutComponent::class)->name('about');
Route::get('/my-account', AccountComponent::class)->name('my-account');
Route::get('/return-policy', ReturnPolicy::class)->name('return-policy');
Route::get('/shipping-policy', ShippingPolicy::class)->name('shipping-policy');
Route::get('/contact', ContactComponent::class)->name('contact');
Route::get('/privacy-policy', PrivacyPolicyComponent::class)->name('privacy-policy');
Route::get('/delivery-information', DeliveryInformationComponent::class)->name('delivery-information');
Route::get('/terms', TermsComponent::class)->name('terms');
Route::get('/cart', CartComponent::class)->name('cart');
Route::get('/checkout', CheckoutComponent::class)->name('checkout');
Route::get('/compare', CompareComponent::class)->name('compare');
Route::get('/shop', ShopComponent::class)->name('shop');
Route::get('/shop-detail/{slug?}/{id}', ShopDetailComponent::class)->name('shop-detail');
Route::get('/wishlist', WishlistComponent::class)->name('wishlist');
Route::get('/coupon-claim', CouponClaim::class)->name('coupon.claim');
Route::get('/user-order', OrderComponent::class)->name('user-order');
Route::get('/user-order-detail/{id}', OrderDetail::class)->name('user-order-detail');
Route::get('/user-profile', Profile::class)->name('user-profile');
Route::get('/user-address', AddressComponent::class)->name('user-address');
// Route::get('/login', LoginComponent::class)->name('login');
Route::get('/register', RegisterComponent::class)->name('register');
Route::get('/order-completed', OrderCompleted::class)->name('order-completed');
Route::get('/all-category', AllCategory::class)->name('all-category');
Route::match(['get', 'post'], '/get-payment', [PaymentSuccessController::class, 'paymentSuccess'])->name('payment.success');
Route::get('/pay-now/{id}', CodConversionComponent::class)->name('pay-now');

Route::get('/ithink-import', [ImportController::class, 'ithink'])->name('ithink');
Route::get('/xprees-bees-import', [ImportController::class, 'xpreesBees'])->name('xpreesBees');
Route::get('/payment-settlement', [ImportController::class, 'paymentSettlement'])->name('paymentSettlement');
Route::get('/meesho-order-import', [ImportController::class, 'meeshoOrderImport']);
Route::get('/meesho-deduction-import', [ImportController::class, 'meeshoDeductionImport']);
Route::get('/meesho-payment-import', [ImportController::class, 'meeshoPaymentImport']);
Route::get('/xpress-bees-rto-import', [ImportController::class, 'xpressBeesRTOImport']);

@include 'admin.php';
